<?php

/**
 * Portfolio cases — generated by bin/scrape-portfolio.php
 * @package Snel
 */

defined('ABSPATH') || exit;

return [
    [
        'title'     => 'Email Lead Scraper - B2B Lead Generation Platform',
        'client'    => 'Snelstack (eigen product)',
        'type'      => 'SaaS Platform',
        'services'  => [
            'Laravel',
            'React',
            'TypeScript',
            'OpenAI',
            'Stripe',
        ],
        'result'    => '2-3 uur research → 2-3 minuten per prospectlijst',
        'url'       => 'https://scraper.loc-nguyen.com',
        'thumb_url' => 'https://snelstack.com/storage/portfolios/01KEF11MJ4MD6X8375C1F2VMYP.png',
        'content'   => '<!-- wp:snel/content -->
<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Het Probleem</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Sales professionals en marketeers besteden 80% van hun tijd aan saaie, handmatige research:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Google Maps doorzoeken, bedrijf voor bedrijf</li>
<li>Websites bezoeken om emailadressen te vinden</li>
<li>Data handmatig kopiëren naar spreadsheets</li>
<li>Gokken welke bedrijven de moeite waard zijn</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Dit kost <strong>2-3 uur per prospectlijst</strong>. Elke keer weer.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/aMd8EoxZGu74u11kTXW8fHO2v9H3AzLbI6DRtadd.png" alt="" /-->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Wat Ik Gebouwd Heb</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Een complete <strong>B2B lead generation tool</strong> die lokale bedrijven vindt, contactgegevens ontdekt, en AI-gestuurde sales strategieën genereert. Alles in één platform.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Van uren naar minuten.</strong> Wat voorheen een middag kostte, duurt nu 2-3 minuten.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Voor Wie Is Dit?</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Gebruiker</th><th>Toepassing</th></tr></thead><tbody><tr><td>Marketing Bureaus</td><td>Lokale MKB\'ers vinden die SEO, webdesign en marketing nodig hebben</td></tr><tr><td>B2B SaaS Bedrijven</td><td>Kleine bedrijven identificeren voor software demos</td></tr><tr><td>Sales Teams</td><td>Gekwalificeerde leads genereren met geverifieerde contactdata</td></tr><tr><td>Freelancers</td><td>Lokale klanten ontdekken voor design, development en copywriting</td></tr><tr><td>Consultants</td><td>Prospectlijsten bouwen voor advies- en accountancydiensten</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Belangrijkste Features</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">1. Slimme Bedrijfszoeker</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Zoek op elke stad, elke branche, elke straal.</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Standaard Zoeken:</strong> 20 bedrijven direct</li>
<li><strong>Super Search:</strong> Eigen grid-algoritme dat <strong>100-500+ bedrijven</strong> vindt in één zoekopdracht</li>
</ul>
<!-- /wp:list -->

<!-- snel:image src="https://snelstack.com/storage/Wikajs4vgJ4pPmOb8KKh3rr81fRo7xNU1jPAVJkU.png" alt="" /-->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">2. Automatische Data Verrijking</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Email Discovery:</strong> Scant websites automatisch voor contactemails</li>
<li><strong>Budget Indicator:</strong> Analyseert email-infrastructuur om bedrijfsbudget in te schatten</li>
<li><strong>Social Media:</strong> Vindt Facebook, Instagram, LinkedIn profielen</li>
<li><strong>Batch Processing:</strong> Verrijk honderden bedrijven tegelijk met real-time voortgang</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">3. AI Sales Intelligence</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>De tool analyseert elke bedrijfswebsite en genereert:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Pijnpunt-analyse met bewijs</li>
<li>Gepersonaliseerde cold email templates</li>
<li>Belscripts met discovery vragen</li>
<li>Service-matching aanbevelingen</li>
</ul>
<!-- /wp:list -->

<!-- snel:image src="https://snelstack.com/storage/JHnybgPsbTiTesxI5cPiF1yzNwqPZHAtap5C8xwU.png" alt="" /-->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">4. Professionele Export</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>PDF Export:</strong> Gepolijste sales documenten voor klantpresentaties</li>
<li><strong>CSV Export:</strong> Gestructureerde data klaar voor CRM import (Salesforce, HubSpot)</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Slimme Techniek Onder De Motorkap</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Grid-Based Super Search</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Google geeft maximaal 20 resultaten per zoekopdracht. Mijn oplossing: het zoekgebied intelligent opdelen in overlappende cellen, elke cel apart doorzoeken, en duplicaten verwijderen via geografische afstandsberekeningen.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Resultaat:</strong> 10-25x meer bedrijven per zoekopdracht.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Intelligente Budget Scoring</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Analyseert MX-records om bedrijfsbudget in te schatten. Bedrijven met Google Workspace of Microsoft 365 scoren hoger - zij hebben budget voor professionele tools.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Real-Time Streaming</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lange zoekopdrachten tonen live voortgang via Server-Sent Events. Gebruikers zien resultaten binnenstromen in plaats van te wachten.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Enterprise Security</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Tweefactorauthenticatie (2FA) met recovery codes, veilige wachtwoordafhandeling, en emailverificatie - dezelfde standaarden als banken.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Het Business Model</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Geen abonnementen - gebruikers kopen credits en betalen alleen wanneer ze zoeken:</p>
<!-- /wp:paragraph -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Pakket</th><th>Prijs</th><th>Credits</th></tr></thead><tbody><tr><td>Starter</td><td>$5</td><td>10</td></tr><tr><td>Basic</td><td>$15</td><td>35</td></tr><tr><td>Pro</td><td>$30</td><td>80</td></tr><tr><td>Business</td><td>$50</td><td>150</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>10 gratis credits</strong> bij registratie</li>
<li>Credits verlopen nooit</li>
<li>Transparante, voorspelbare kosten</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Technologie Stack</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Categorie</th><th>Technologie</th></tr></thead><tbody><tr><td>Backend</td><td>Laravel 12 (PHP 8.2)</td></tr><tr><td>Frontend</td><td>React 19, TypeScript, Tailwind CSS 4</td></tr><tr><td>UI Components</td><td>Radix UI (accessibility-focused)</td></tr><tr><td>Payments</td><td>Stripe (Cards + iDEAL)</td></tr><tr><td>AI</td><td>OpenAI GPT-4o-mini</td></tr><tr><td>Maps</td><td>Google Maps & Places API</td></tr><tr><td>Auth</td><td>Laravel Fortify met 2FA</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Opgeleverde Waarde</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Resultaat</th><th>Impact</th></tr></thead><tbody><tr><td>Tijdsbesparing</td><td>2-3 uur research → 2-3 minuten</td></tr><tr><td>ROI</td><td>Eén geconverteerde lead betaalt tientallen zoekopdrachten</td></tr><tr><td>Datakwaliteit</td><td>Geverifieerde emails verlagen bounce rates</td></tr><tr><td>Concurrentievoordeel</td><td>AI sales plans maken elke verkoper effectiever</td></tr><tr><td>Laag Risico</td><td>Geen abonnementen, betaal alleen wat je gebruikt</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Live Demo</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong><a href="https://scraper.loc-nguyen.com/">scraper.loc-nguyen.com</a></strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><em>Dit is een volledig productie-klare SaaS applicatie die expertise demonstreert in moderne web development, third-party API integratie, betalingsverwerking, AI implementatie, en user experience design.</em></p>
<!-- /wp:paragraph -->
<!-- /wp:snel/content -->',
    ],
    [
        'title'     => 'Morris & Bella - Custom Restaurant Theme',
        'client'    => 'Morris & Bella',
        'type'      => 'Custom WordPress',
        'services'  => [
            'WordPress',
            'React',
            'Tailwind CSS',
            'PHP',
        ],
        'result'    => 'Van Squarespace naar razendsnelle WordPress met volledige klantcontrole',
        'url'       => '',
        'thumb_url' => 'https://snelstack.com/storage/portfolios/01KEF3GP1WBJ0C847CPQ70K3ZR.png',
        'content'   => '<!-- wp:snel/content -->
<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">De Vraag</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Morris &amp; Bella is een plant-based restaurant met een sterke visuele identiteit. Ze zaten vast aan een Squarespace website die traag was en beperkt in mogelijkheden. Elke aanpassing kostte moeite, de laadtijden waren slecht, en ze hadden geen echte controle over hun eigen site.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ze wilden:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Snelle website</strong> - geen Squarespace traagheid meer</li>
<li><strong>Volledige controle</strong> over elke sectie</li>
<li><strong>Zelf content beheren</strong> zonder afhankelijk te zijn van een developer</li>
<li><strong>Premium uitstraling</strong> die past bij hun merk</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Wat Ik Gebouwd Heb</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Een volledig custom WordPress theme met eigen Gutenberg blocks. Geen Elementor, geen WPBakery, geen plugins. Pure WordPress met moderne development practices.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ik heb Next.js gebruikt om snel te prototypen en het design uit te werken. Daarna alles vertaald naar een production-ready WordPress theme.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>De klant beheert nu zelf hun menu\'s, afbeeldingen en teksten - via de native WordPress editor. En de site laadt in een fractie van de tijd vergeleken met hun oude Squarespace.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Custom Gutenberg Blocks</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Ik heb 9 custom blocks gebouwd die de klant vrij kan gebruiken:</p>
<!-- /wp:paragraph -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Block</th><th>Functie</th></tr></thead><tbody><tr><td>Hero Section</td><td>Fullscreen beeld met overlay en animaties</td></tr><tr><td>Info Section</td><td>Tekst met feature cards en prijzen</td></tr><tr><td>Menu Carousel</td><td>Swipeable menu items met touch support</td></tr><tr><td>Suppliers</td><td>Leveranciers met alternerende layout</td></tr><tr><td>Contact Form</td><td>Formulier + Google Maps + openingstijden</td></tr><tr><td>Newsletter</td><td>Email signup met validatie</td></tr><tr><td>Blog Grid</td><td>Dynamische WordPress posts</td></tr><tr><td>Menu Items</td><td>Gerechten met prijzen en dieet-info</td></tr><tr><td>Press Section</td><td>Badges en persaandacht</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph -->
<p>Elke block is volledig aanpasbaar via de WordPress editor. Geen code nodig.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">De Technische Aanpak</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Design → Prototype → WordPress</h3>
<!-- /wp:heading -->

<!-- wp:list {"ordered":true} -->
<ol class="wp-block-list">
<li><strong>Design in Next.js</strong> - Snel itereren en experimenteren</li>
<li><strong>Goedkeuring klant</strong> - Live prototype om feedback te verzamelen</li>
<li><strong>WordPress conversie</strong> - Elk component vertaald naar Gutenberg block</li>
</ol>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Next.js Prototype  →  WordPress Theme
├── React JSX      →  edit.js (editor)
├── Props          →  block.json (attributes)
├── Render         →  render.php (frontend)
└── Interactivity  →  view.js (animaties)</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Modern Build System</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Geen handmatige CSS bestanden. Alles draait op:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Tailwind CSS v4</strong> - Snelle styling</li>
<li><strong>npm scripts</strong> - <code>npm run build</code> voor productie</li>
<li><strong>Hot reload</strong> - Wijzigingen direct zichtbaar</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Performance First</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Hun Squarespace site was traag. Deze niet:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Geen zware plugins</li>
<li>Geoptimaliseerde assets</li>
<li>Lazy loading afbeeldingen</li>
<li>Minified CSS/JS</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Wat De Klant Nu Kan</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Zelf Beheren</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Menu items toevoegen en aanpassen</li>
<li>Afbeeldingen uploaden en croppen</li>
<li>Teksten wijzigen</li>
<li>Blog posts publiceren</li>
<li>Openingstijden aanpassen</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Zonder Developer</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Geen code kennis nodig</li>
<li>Drag &amp; drop blocks</li>
<li>Live preview in editor</li>
<li>Revisies en undo</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Technologie Stack</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Categorie</th><th>Technologie</th></tr></thead><tbody><tr><td>CMS</td><td>WordPress 6.4</td></tr><tr><td>Editor</td><td>Gutenberg (native)</td></tr><tr><td>Blocks</td><td>Custom React components</td></tr><tr><td>Styling</td><td>Tailwind CSS v4</td></tr><tr><td>Colors</td><td>OKLCH color space</td></tr><tr><td>Build</td><td>npm + webpack</td></tr><tr><td>Fonts</td><td>Cormorant Garamond + Inter</td></tr><tr><td>PHP</td><td>8.0+</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Squarespace vs Custom WordPress</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th></th><th>Squarespace</th><th>Custom WordPress</th></tr></thead><tbody><tr><td>Snelheid</td><td>Traag</td><td>Snel</td></tr><tr><td>Flexibiliteit</td><td>Beperkt</td><td>Onbeperkt</td></tr><tr><td>Eigenaarschap</td><td>Gehuurd</td><td>Eigen bezit</td></tr><tr><td>Maandkosten</td><td>€20-40/maand</td><td>Alleen hosting</td></tr><tr><td>Controle</td><td>Template-gebonden</td><td>Volledige vrijheid</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Waarom Custom Blocks?</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>De meeste WordPress developers gebruiken pagebuilders: Elementor, Divi, WPBakery. Waarom ik niet?</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Pagebuilders:</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Laden 500KB+ extra JavaScript</li>
<li>Maken sites traag</li>
<li>Locken je in hun ecosysteem</li>
<li>Complexe, verwarrende interface</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>Custom Gutenberg Blocks:</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Native WordPress, geen plugins</li>
<li>Minimale overhead</li>
<li>Volledige controle over output</li>
<li>Cleane, onderhoudbare code</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Het kost meer tijd om te bouwen, maar het resultaat is een site die jarenlang snel en stabiel blijft.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><em>Van Squarespace naar een snelle, flexibele WordPress site. Neem contact op voor een gesprek.</em></p>
<!-- /wp:paragraph -->
<!-- /wp:snel/content -->',
    ],
    [
        'title'     => 'DroneStart v4 - Compliance Platform voor Drone Operators',
        'client'    => 'DroneStart',
        'type'      => 'SaaS Platform',
        'services'  => [
            'Laravel',
            'React',
            'TypeScript',
            'Inertia.js',
            'MySQL',
        ],
        'result'    => 'Uren handmatig werk geëlimineerd per template-update',
        'url'       => '',
        'thumb_url' => 'https://snelstack.com/storage/portfolios/01KECNC9RWPA0RFBXEAS8XSYEN.png',
        'content'   => '<!-- wp:snel/content -->
<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">De Uitdaging</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>DroneStart helpt professionele drone-operators in Nederland om wettelijk compliant te blijven. Operators moeten gedetailleerde technische handboeken bijhouden met hun apparatuur, procedures en veiligheidsprotocollen.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Hun bestaande systeem was aan vervanging toe:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Trage, verouderde interface</strong> die gebruikers frustreerde</li>
<li><strong>Lastig te onderhouden</strong> waardoor updates lang duurden</li>
<li><strong>Performance problemen</strong> bij dagelijks gebruik</li>
<li><strong>Niet schaalbaar</strong> voor toekomstige groei</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Ze hadden geen oplapwerk nodig, maar een complete herbouw.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/xnrKW0QkwbA9UUKzDdlvxmca9giQ5mGAxl0gAfbQ.png" alt="" /-->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Wat Ik Gebouwd Heb</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Een volledig nieuw platform, vanaf de grond opgebouwd met moderne technologie.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/zOW0jnNIvFMSCHf65nEaMIxl22jnPq21L5DPcqKN.png" alt="" /-->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Voor Drone Operators (Klanten)</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Professionele handboeken maken die voldoen aan luchtvaartautoriteiten</li>
<li>Documenten uploaden en organiseren (certificaten, handleidingen, goedkeuringen)</li>
<li>Kant-en-klare templates gebruiken voor snelle documentatie</li>
<li>Werken in Nederlands of Engels</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Voor DroneStart (Beheerders)</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Templates aanmaken die automatisch doorstromen naar klant-handboeken</li>
<li>Gebruikers en rechten beheren</li>
<li>Alle activiteit en wijzigingen volgen</li>
<li>Nieuwe klanten uitnodigen via email</li>
</ul>
<!-- /wp:list -->

<!-- snel:image src="https://snelstack.com/storage/dC4jLPGrB2aPGEov6RAjm5VSvKZrUKKQt3LfeOvZ.png" alt="" /-->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">De Killer Feature: Slimme Template Propagatie</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Dit is het hart van het systeem.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Wanneer DroneStart een template aanpast - bijvoorbeeld voor nieuwe regelgeving - dan werkt het systeem <strong>automatisch alle klant-handboeken bij</strong> die dat template gebruiken. Direct. Zonder handmatig werk.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Voorheen:</strong> Honderden documenten handmatig doorlopen en aanpassen.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Nu:</strong> Één wijziging, automatisch overal doorgevoerd.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/2JJewsgyKpu3G0P6Ki2AzBZtMI7Bai0SwjLfqYAI.png" alt="" /-->

<!-- wp:paragraph -->
<p>Dit bespaart letterlijk uren werk per template-update.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Professionele Landing Page</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Naast het platform heb ik ook een complete <strong>marketing landing page</strong> ontworpen en gebouwd. Een pagina die bezoekers overtuigt en converteert naar klanten.</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Moderne, strakke vormgeving</strong> die vertrouwen wekt</li>
<li><strong>Duidelijke call-to-actions</strong> die bezoekers naar actie leiden</li>
<li><strong>Geoptimaliseerd voor conversie</strong> met social proof en feature highlights</li>
<li><strong>Volledig responsive</strong> - perfect op elk apparaat</li>
<li><strong>SEO-ready</strong> voor betere vindbaarheid</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>De landing page is het visitekaartje van DroneStart - de eerste indruk die potentiële klanten krijgen.
<img src="https://snelstack.com/storage/zufTnvFkxCfFLtHWluwo9GKE4rGTLgfiZzIZKCto.png" alt=""></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Opgeleverde Waarde</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Resultaat</th><th>Impact</th></tr></thead><tbody><tr><td>Tijdsbesparing</td><td>Uren handmatig werk weg per template-wijziging</td></tr><tr><td>Gebruikersgemak</td><td>Moderne interface, tevreden klanten</td></tr><tr><td>Betrouwbaarheid</td><td>Professionele beveiliging en databescherming</td></tr><tr><td>Schaalbaarheid</td><td>Klaar voor groei van tientallen naar duizenden users</td></tr><tr><td>Onderhoudbaarheid</td><td>Schone codebase, makkelijk uit te breiden</td></tr><tr><td>Conversie</td><td>Landing page die bezoekers omzet in klanten</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Onder De Motorkap</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Architectuur</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Backend:</strong> Laravel 12 met queue workers voor zware taken op de achtergrond</li>
<li><strong>Frontend:</strong> React 19 + TypeScript via Inertia.js voor snelle, moderne UI</li>
<li><strong>Database:</strong> MySQL met Redis caching voor performance</li>
<li><strong>Real-time:</strong> Wijzigingen direct zichtbaar zonder pagina te verversen</li>
<li><strong>Tweetalig:</strong> Volledige Nederlandse en Engelse ondersteuning</li>
<li><strong>Responsive:</strong> Werkt perfect op desktop, tablet en mobiel</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Gebouwde Features</h3>
<!-- /wp:heading -->

<!-- wp:list {"ordered":true} -->
<ol class="wp-block-list">
<li><strong>Slimme Document Editor</strong> - Rich text bewerking met versiegeschiedenis</li>
<li><strong>Automatische Propagatie</strong> - Template wijzigingen stromen door naar alle gekoppelde documenten</li>
<li><strong>Activiteiten Log</strong> - Complete audit trail van alle acties in het systeem</li>
<li><strong>Uitnodigingssysteem</strong> - Veilige onboarding via email</li>
<li><strong>Bestandsbeheer</strong> - Georganiseerde opslag voor afbeeldingen en documenten</li>
<li><strong>Zoekfunctie</strong> - Doorzoek templates, gebruikers en content</li>
<li><strong>Dashboard</strong> - Statistieken en inzichten in één oogopslag</li>
<li><strong>Landing Page</strong> - Converterende marketing pagina</li>
</ol>
<!-- /wp:list -->

<!-- snel:image src="https://snelstack.com/storage/SR6VbXGdG2IsFfFXZtMwW8FtkZUSIULg39DgkXaX.png" alt="" /-->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Project In Cijfers</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th></th><th></th></tr></thead><tbody><tr><td>Regels Code</td><td>25.000+</td></tr><tr><td>API Endpoints</td><td>40+</td></tr><tr><td>Automated Tests</td><td>73</td></tr><tr><td>Ondersteunde Talen</td><td>2 (NL/EN)</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Waarom Dit Project Bijzonder Is</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>Volledige Eigenaarschap</strong>
Van database-ontwerp tot deployment - alles zelf gebouwd en opgeleverd.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Legacy Integratie</strong>
Naadloos verbonden met de bestaande Firebase database terwijl de hele frontend gemoderniseerd werd.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Productie-Klaar</strong>
Geen demo of prototype - dit draait live en bedient echte klanten.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Complexe Problemen Opgelost</strong>
Real-time template propagatie, multi-tenant architectuur, en tweelaagsauthenticatie waren allemaal uitdagingen die ik moest tackelen.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><img src="https://snelstack.com/storage/EPHHpphjzdQKx3lO4q6P7p83q622IrtOvB3FPX3X.png" alt="">
<img src="https://snelstack.com/storage/yRGGRgW5cJKkSuS1kMjyB3NYwaLpyXIcJ80SkS6i.png" alt=""></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>"Het nieuwe DroneStart platform heeft getransformeerd hoe we onze klanten bedienen. Wat voorheen uren duurde, gebeurt nu automatisch."</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><em>Zelf een platform nodig dat jouw business transformeert? Laten we kennismaken.</em></p>
<!-- /wp:paragraph -->
<!-- /wp:snel/content -->',
    ],
    [
        'title'     => 'TaxiNL - Online Taxi Boekingsplatform',
        'client'    => 'Snelstack (eigen product)',
        'type'      => 'White-label Product',
        'services'  => [
            'Next.js',
            'React',
            'TypeScript',
            'Stripe',
            'iDEAL',
        ],
        'result'    => '70%+ minder inkomende telefoontjes, 24/7 boekingen',
        'url'       => 'https://taxi.loc-nguyen.com',
        'thumb_url' => 'https://snelstack.com/storage/portfolios/01KEF1GJXYXD7WGAS11XXQZT9C.png',
        'content'   => '<!-- wp:snel/content -->
<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Het Probleem</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Taxibedrijven in Nederland verliezen klanten aan Uber en Bolt. Waarom? Omdat boeken bij een traditioneel taxibedrijf betekent:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Bellen en wachten</strong> - niemand wil meer bellen</li>
<li><strong>Geen prijsindicatie</strong> - pas achteraf weten wat het kost</li>
<li><strong>Geen online betaling</strong> - contant of pinnen in de auto</li>
<li><strong>Alleen Nederlands</strong> - toeristen en expats haken af</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Klanten verwachten in 2025 een <strong>Uber-achtige ervaring</strong>. De meeste taxibedrijven kunnen dat niet bieden.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/hJe0aKKjhD8NU0QGNoZ4bjwGkDFAOTsWZsLjcs0i.png" alt="" /-->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Wat Ik Gebouwd Heb</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Een compleet <strong>online taxi boekingsplatform</strong> dat elk taxibedrijf kan gebruiken. Klanten boeken zelf, betalen vooraf, en het bedrijf ontvangt alleen bevestigde ritten.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Van telefoontjes naar online boekingen.</strong> 24/7 beschikbaar, geen personeel nodig.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">De Klantervaring</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Stap 1: Route Invoeren</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Adres autocomplete speciaal voor Nederlandse adressen. Klant ziet direct de route op de kaart met afstand en geschatte reistijd.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Stap 2: Bagage Aangeven</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Hoeveel koffers? Handbagage? Het systeem berekent of er extra kosten zijn.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Stap 3: Voertuig Kiezen</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Van standaard tot minivan - elk voertuigtype met eigen prijs, capaciteit en foto.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Stap 4: Betalen</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Veilig afrekenen via Stripe. Creditcard of iDEAL - de betaalmethode die Nederlanders vertrouwen.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/Ne9NI2MHagO0T6hRYX6E04jhmonDrcE2fGD3uaLr.png" alt="" /-->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Slimme Prijsberekening</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Het systeem berekent automatisch de juiste prijs op basis van:</p>
<!-- /wp:paragraph -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Factor</th><th>Voorbeeld</th></tr></thead><tbody><tr><td>Afstand</td><td>€2,50 per kilometer</td></tr><tr><td>Reistijd</td><td>€0,40 per minuut</td></tr><tr><td>Voertuigtype</td><td>Minivan +50%, Business +35%</td></tr><tr><td>Nachttarief</td><td>+25% tussen 23:00-06:00</td></tr><tr><td>Weekendtarief</td><td>+15% op zaterdag en zondag</td></tr><tr><td>Luchthaven</td><td>+€5 toeslag voor Schiphol pickup</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph -->
<p>Transparant voor de klant. Geen verrassingen achteraf.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Features Die Het Verschil Maken</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Nederlandse Adres Autocomplete</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Gekoppeld aan PDOK Locatieserver - de officiële database van alle Nederlandse adressen. Geen Google Maps kosten.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Interactieve Routekaart</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Klanten zien hun exacte route voordat ze boeken. Geeft vertrouwen en voorkomt misverstanden.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Tweetalig (NL/EN)</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Eén klik om te wisselen tussen Nederlands en Engels. Perfect voor toeristen, expats en internationale zakenreizigers.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">iDEAL Betalingen</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Nederlanders betalen het liefst met iDEAL. Volledig geïntegreerd naast creditcard opties.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Mobiel-First Design</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>70% van de boekingen komt via smartphone. Deze app is daar specifiek voor geoptimaliseerd.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/mu3tD3OwmBoQ4T8tJxHPCaxhCStL043mnh83fE3s.png" alt="" /-->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Lighthouse Scores</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Metric</th><th>Score</th></tr></thead><tbody><tr><td>Performance</td><td>90+</td></tr><tr><td>Accessibility</td><td>95+</td></tr><tr><td>Best Practices</td><td>100</td></tr><tr><td>SEO</td><td>100</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph -->
<p>Niet zomaar een mooie website - een <strong>technisch perfecte</strong> website.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Technologie Stack</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Categorie</th><th>Technologie</th></tr></thead><tbody><tr><td>Framework</td><td>Next.js 16</td></tr><tr><td>Frontend</td><td>React 19, TypeScript</td></tr><tr><td>Styling</td><td>Tailwind CSS 4</td></tr><tr><td>Components</td><td>Radix UI</td></tr><tr><td>Payments</td><td>Stripe (Cards + iDEAL)</td></tr><tr><td>Maps</td><td>Leaflet + OpenStreetMap</td></tr><tr><td>Adressen</td><td>PDOK Locatieserver API</td></tr><tr><td>Routes</td><td>OSRM (Open Source Routing)</td></tr><tr><td>i18n</td><td>next-intl</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Business Waarde Voor Taxibedrijven</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Resultaat</th><th>Impact</th></tr></thead><tbody><tr><td>Minder telefoontjes</td><td>70%+ reductie in inkomende calls</td></tr><tr><td>24/7 Boekingen</td><td>Klanten boeken ook \'s nachts en in het weekend</td></tr><tr><td>Betere cashflow</td><td>Vooraf betaald, geen no-shows</td></tr><tr><td>Internationaal bereik</td><td>Engelse versie trekt toeristen en expats</td></tr><tr><td>Professionele uitstraling</td><td>Concurreren met Uber op user experience</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Live Demo</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong><a href="https://taxi.loc-nguyen.com/">taxi.loc-nguyen.com</a></strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Probeer het zelf - doorloop de hele booking flow tot aan de betaalpagina.</p>
<!-- /wp:paragraph -->
<!-- /wp:snel/content -->',
    ],
    [
        'title'     => 'Geautomatiseerde Email Sequentie met n8n & Notion',
        'client'    => 'Snelstack (eigen systeem)',
        'type'      => 'Automatisering',
        'services'  => [
            'n8n',
            'Notion',
            'JavaScript',
            'Microsoft Outlook',
        ],
        'result'    => '4+ uur per week bespaard, 100% follow-up rate',
        'url'       => '',
        'thumb_url' => 'https://snelstack.com/storage/portfolios/01KEBRSJRWN0XTMFA6XCQP2Q7Y.png',
        'content'   => '<!-- wp:snel/content -->
<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Het Probleem</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Handmatig leads opvolgen is tijdrovend en foutgevoelig. Je vergeet follow-ups, stuurt dubbele emails, of overschrijdt de dagelijkse verzendlimiet van je email accounts. Het resultaat: gemiste kansen en slechte deliverability.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">De Oplossing</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Een volledig geautomatiseerd email sequentie systeem gebouwd met <strong>n8n</strong> en <strong>Notion</strong> dat:</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Slim capaciteitsbeheer</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Berekent automatisch hoeveel emails er vandaag verstuurd mogen worden</li>
<li>Houdt rekening met email warm-up limieten per account</li>
<li>Prioriteert follow-ups boven nieuwe leads</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>5-Staps Email Sequentie</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Email 1: Eerste contact</li>
<li>Email 2-5: Automatische follow-ups na X dagen</li>
<li>Elke email heeft een eigen template per sector</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>Automatische Sender Rotatie</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Roteert tussen meerdere email accounts</li>
<li>Voorkomt dat één account overbelast wordt</li>
<li>Verbetert deliverability en voorkomt spam flags</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>Notion als CRM</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Alle leads beheerd in Notion database</li>
<li>Status tracking (responded, not interested, invalid email)</li>
<li>Automatische updates na elke verstuurde email</li>
</ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>Dagelijkse Rapportage</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Ontvangt elke ochtend een samenvatting</li>
<li>Overzicht van capaciteit en geplande emails</li>
<li>Volledige transparantie over de campagne</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Technische Details</h3>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Component</th><th>Technologie</th></tr></thead><tbody><tr><td>Workflow Engine</td><td>n8n (self-hosted)</td></tr><tr><td>CRM / Database</td><td>Notion API</td></tr><tr><td>Email Verzending</td><td>Microsoft Outlook API</td></tr><tr><td>Scheduling</td><td>Cron-based triggers</td></tr><tr><td>Logic</td><td>Custom JavaScript nodes</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Workflow Architectuur</h3>
<!-- /wp:heading -->

<!-- snel:image src="https://snelstack.com/storage/n8XEpIrmjpaW32YLPVPpb20qpTx66EiZwyLQER6q.png" alt="" /-->

<!-- wp:code -->
<pre class="wp-block-code"><code>[Schedule Trigger]
          |
          v
  [Notion: Haal Leads]
          |
          v
  [Bereken Capaciteit]
          |
          v
  [Groepeer per Email Stap]
          |
     +----|----+----+----+
     v    v    v    v    v
   [E1] [E2] [E3] [E4] [E5]
     |    |    |    |    |
     +----+----+----+----+
          |
          v
  [Sender Rotatie]
          |
          v
  [Verstuur Email]
          |
          v
  [Update Notion]
          |
          v
  [Stuur Rapport]</code></pre>
<!-- /wp:code -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Hoe Het Werkt</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>Stap 1: Trigger &amp; Data Ophalen</strong>
De workflow start dagelijks op een vast tijdstip. Eerst worden alle actieve leads uit Notion opgehaald, samen met de email warm-up configuratie.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Stap 2: Capaciteit Berekenen</strong>
Het systeem berekent hoeveel emails er vandaag verstuurd mogen worden op basis van de warm-up limieten van alle gekoppelde email accounts.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Stap 3: Leads Groeperen</strong>
Elke lead wordt ingedeeld bij de juiste email stap (1 t/m 5) op basis van wanneer de laatste email is verstuurd en hoeveel dagen er sindsdien zijn verstreken.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Stap 4: Emails Versturen</strong>
Per email stap worden de leads verwerkt. Het systeem selecteert automatisch een beschikbare sender, verstuurt de email via Outlook, en werkt de lead status bij in Notion.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/eGYLKYBiftHtQOFCwkz3NfFCGCrRUN5fMZmg8wn3.png" alt="" /-->

<!-- wp:paragraph -->
<p><strong>Stap 5: Rapportage</strong>
Na afloop ontvang je een samenvatting met het aantal verstuurde emails per stap, de resterende capaciteit, en eventuele errors.</p>
<!-- /wp:paragraph -->

<!-- snel:image src="https://snelstack.com/storage/MElyVKGEvSIfV6rU1CVI6FuQqbjibGEfcT4frbl8.png" alt="" /-->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Resultaten</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>4+ uur per week bespaard</strong> aan handmatige opvolging</li>
<li><strong>100% follow-up rate</strong> - geen lead wordt vergeten</li>
<li><strong>Verbeterde deliverability</strong> door sender rotatie</li>
<li><strong>Hogere response rate</strong> door consistente timing</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Voor Wie Is Dit?</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Dit systeem is ideaal voor:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>Sales teams</strong> die koude acquisitie doen</li>
<li><strong>Freelancers</strong> die leads willen opvolgen</li>
<li><strong>Agencies</strong> met meerdere outreach campagnes</li>
<li><strong>Startups</strong> die hun sales willen automatiseren</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Wil je dit ook?</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Ik bouw dit soort automatiseringen op maat. Of het nu gaat om email sequences, lead capture, of complete sales funnels - binnen 2 weken draait jouw systeem.</p>
<!-- /wp:paragraph -->
<!-- /wp:snel/content -->',
    ],
    [
        'title'     => 'StopAbbo',
        'client'    => 'Snelstack (eigen product)',
        'type'      => 'SaaS Product',
        'services'  => [
            'Laravel',
            'React',
            'TypeScript',
            'Mollie',
            'MySQL',
        ],
        'result'    => 'Volledig geautomatiseerd zonder menselijke tussenkomst',
        'url'       => '',
        'thumb_url' => 'https://snelstack.com/storage/portfolios/01KE9XYZ7M8PPN846PS8X6X1GX.png',
        'content'   => '<!-- wp:snel/content -->
<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Het Probleem</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Abonnementen opzeggen is frustrerend. Mensen hebben sportschoolabonnementen, streamingdiensten, verzekeringen en dating-apps - maar als ze willen opzeggen, maken bedrijven het expres moeilijk. Lange telefoontjes, verborgen opzegpagina\'s, of complexe papierwerk.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ik bouwde StopAbbo: een geautomatiseerde opzegservice die alles afhandelt in minder dan 2 minuten.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Hoe Het Werkt</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Stap</th><th>Wat Gebeurt Er</th><th>Tijd</th></tr></thead><tbody><tr><td>1. Zoeken</td><td>Klant typt bedrijfsnaam, directe resultaten verschijnen</td><td>10 sec</td></tr><tr><td>2. Formulier</td><td>Simpel formulier: naam, adres, email, gewenste opzegdatum</td><td>60 sec</td></tr><tr><td>3. Betalen</td><td>€9.98 betaling, officiële opzegbrief wordt automatisch verstuurd</td><td>30 sec</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph -->
<p>Na betaling:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Professionele PDF opzegbrief direct gegenereerd</li>
<li>Brief binnen seconden naar klant gemaild</li>
<li>Inclusief wettelijke AVG/GDPR gegevensverwijdering verzoek</li>
<li>Confetti-animatie op de bedankpagina</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Belangrijkste Features</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Slimme Zoekfunctie</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Real-time zoeken door honderden bedrijven. Terwijl gebruikers typen, verschijnen matchende bedrijven direct met categorielabels. Geen pagina-refreshes, geen wachten.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Intelligente Formulieren</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Valideert alle velden real-time</li>
<li>Toont fouten duidelijk met visuele indicatoren</li>
<li>Telefoonnummer invoer met landcode ondersteuning</li>
<li>Datumkiezer voor opzegtiming</li>
<li>Live preview van de opzegbrief tijdens invullen</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Naadloze Betalingen</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Geïntegreerd met Mollie (Europa\'s grootste betaalprovider):</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Veilige checkout</li>
<li>Ondersteunt iDEAL, creditcards, PayPal en meer</li>
<li>Automatische orderverwerking na betalingsbevestiging</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Geautomatiseerd Email Systeem</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Wanneer betaling slaagt, doet het systeem automatisch:</p>
<!-- /wp:paragraph -->

<!-- wp:list {"ordered":true} -->
<ol class="wp-block-list">
<li>Genereert een professionele PDF opzegbrief</li>
<li>Mailt deze naar de klant met volledige orderdetails</li>
<li>Notificeert het team van de nieuwe order</li>
<li>Allemaal binnen seconden - geen handmatig werk</li>
</ol>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Juridisch Correcte Documenten</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>De PDF brief bevat:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Formele zakelijke brief opmaak</li>
<li>Klantgegevens en abonnementsreferentie</li>
<li>Officieel opzegverzoek</li>
<li>AVG Artikel 17 gegevensverwijdering verzoek</li>
<li>Professioneel handtekeningblok</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Bedrijfsmodel</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Metric</th><th>Waarde</th></tr></thead><tbody><tr><td>Prijs per opzegging</td><td>€9.98</td></tr><tr><td>Doelmarkt</td><td>Nederland</td></tr><tr><td>Verdienmodel</td><td>Per-transactie fee</td></tr><tr><td>Winstmarge</td><td>Hoog (geautomatiseerd, bijna geen marginale kosten)</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph -->
<p>Mensen betalen graag €10 om 30+ minuten frustratie met klantenservice te vermijden.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Technische Stack</h2>
<!-- /wp:heading -->

<!-- wp:table -->
<figure class="wp-block-table"><table><thead><tr><th>Component</th><th>Technologie</th></tr></thead><tbody><tr><td>Frontend</td><td>React + TypeScript</td></tr><tr><td>Backend</td><td>Laravel (PHP)</td></tr><tr><td>Database</td><td>MySQL</td></tr><tr><td>Betalingen</td><td>Mollie API</td></tr><tr><td>PDF Generatie</td><td>mPDF</td></tr><tr><td>Email</td><td>Geautomatiseerde SMTP</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Architectuur Beslissingen</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list">
<li><strong>UUID order IDs</strong> — veilige, niet-raadbare ordernummers</li>
<li><strong>Webhook-based payments</strong> — handelt async betalingsbevestigingen betrouwbaar af</li>
<li><strong>Mobile-first design</strong> — werkt perfect op telefoons</li>
<li><strong>SEO geoptimaliseerd</strong> — categoriepagina\'s ranken voor "[bedrijfsnaam] opzeggen" zoekopdrachten</li>
</ul>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2 class="wp-block-heading">Resultaat</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Een volledig werkend SaaS product dat:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list">
<li>Orders automatisch verwerkt zonder menselijke tussenkomst</li>
<li>Schaalt zonder extra personeel</li>
<li>Echte betalingen verwerkt via Mollie</li>
<li>Juridisch correcte documenten genereert</li>
<li>Klanten een frustrerende taak bespaart</li>
</ul>
<!-- /wp:list -->
<!-- /wp:snel/content -->',
    ],
];
